# The title of the photoalbum
TITLE='A simple Photoalbum'

# Thumbnail height geometry
THUMBHEIGHT=300
# Normal geometry height (when viewing photo). Uncomment, to keep original size.
HEIGHT=1200
# Max previews per page.
MAXPREVIEWS=40

# Diverse directories, need to be full paths, not relative!
INCOMING_DIR=$(pwd)/incoming
DIST_DIR=$(pwd)/dist
TEMPLATE_DIR=/usr/share/photoalbum/templates/default
#TEMPLATE_DIR=/usr/share/photoalbum/templates/minimal

# Includes a .tar of the incoming dir in the dist, can be yes or no
TARBALL_INCLUDE=yes
TARBALL_SUFFIX=.tar
TAR_OPTS='-c'

# Some debugging options
#set -e
#set -x
